global:
  security:
    allowInsecureImages: true

replicaCount: 1
image:
  registry: public.ecr.aws
  repository: bitnami/mariadb-galera
  tag: 10.6.8-debian-11-r18
existingSecret: "mariadb-galera-secret"
db:
  user: "appuser"
  name: ""
persistence:
  enabled: true
  size: 50Gi
  storageClass: "longhorn"
resources:
  requests:
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
service:
  type: LoadBalancer
galera:
  bootstrap:
    forceBootstrap: false
metrics:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/mysqld-exporter
    tag: 0.17.2-debian-12-r16
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
networkPolicy:
  enabled: true
